/etc/nginx/sites-enabled/calden.ortspage.de.conf
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name calden.ortspage.de;

    root /var/www/ortspage.de/public;

    ssl_certificate     /etc/letsencrypt/live/calden.ortspage.de/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/calden.ortspage.de/privkey.pem;

    access_log /var/log/nginx/calden.ortspage.de-access.log;
    error_log  /var/log/nginx/calden.ortspage.de-error.log warn;

    set $php_upstream unix:/run/php/php8.5-fpm.sock;
    include /etc/nginx/snippets/typo3-common.conf;
}

server {
    listen 80;
    listen [::]:80;
    server_name calden.ortspage.de;
    return 301 https://$host$request_uri;
}
